mozilla/webextension-polyfill

- .travis.yml
This PR configures travis to publish a tagged release on npm from travis. (fix #33)
> chore: Publish tagged releases to npm from travis job

- .eslintrc
This is what's shown on my computer:
```
.../webextension-polyfill/src/browser-polyfill.js
7:1  error  'use strict' is unnecessary inside of modules  strict
.../webextension-polyfill/Gruntfile.js
3:1  error  'use strict' is unnecessary inside of modules   strict
36:1  error  Expected indentation of 18 spaces but found 28  indent
37:1  error  Expected indentation of 18 spaces but found 28  indent
```
* `indent` errors will be fixed by #42
* `strict` errors are due to rules defined in my own `/.eslintrc` and disappear after this PR.
> Limit eslint to the project's own rules

- api-metadata.json
- src/browser-polyfill.js
- test/test-async-functions.js
- test/test-proxied-properties.js
This PR is applying the following changes to fix #56:
- the changes into api-metadata.json, needed to instruct the polyfill to wrap the devtools API namespace)
- a fix in the base browser-polyfill.js module to prevent the `TypeError` exception when the getter on the proxy is related to a non-configurable read-only property of the original Proxy target (fixed by using an empty object which has the original target as its prototype as the "root" target of the Proxy instance created by the polyfill)
- a fix in the base browser-polyfill.js module to force devtools.panels.create to return a promise that resolves to a single callback argument (instead of an resolving to an array of arguments which contains an additional undocumented second parameter)
- fix applied on one of the existent tests …
> feat: Add support for wrapping the devtools APIs

- src/browser-polyfill.js
- test/test-proxied-properties.js
This PR contains changes which aims to fix #58 using a strategy that it is also able to fix the `Proxy TypeError` issues related to the devtools API namespace (#57).
> fix: Prevent 'Previous API instantiation failed' errors on runtime.sendMessage API calls

- api-metadata.json
_Promisify_ the [`browser.identity.launchWebAuthFlow()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/identity/launchWebAuthFlow) function (available since _Firefox 53_).
> feat: add identity.launchWebAuthFlow() in metadata.

- .travis.yml
- test/integration/setup.js
- test/integration/test-runtime-messaging-on-chrome.js
The integration tests are currently failing on Travis because it seems to be unable to run chrome without passing the --no-sandbox chrome CLI option:
- https://travis-ci.org/mozilla/webextension-polyfill/builds/326860218#L1864
This PR applies the changes needed to pass the --no-sandbox option to puppeteer if the integration tests are running in a Travis CI job.
> fix: Pass --no-sandbox chrome CLI option when running the integration tests on travis

- api-metadata.json
- src/browser-polyfill.js
- test/fixtures/runtime-messaging-extension/background.js
- test/fixtures/runtime-messaging-extension/manifest.json
- test/test-async-functions.js
This PR contains the changes to the api-metadata.json from #9 and it also applies the changes needed into the polyfill wrappers to be able to customize the wrapper behavior for the API methods that returns a Promise on Firefox but do not accept a callback on Chrome (which is the case for pageAction.show and hide).
> Fix: Support pageAction show/hide wrapping

- .travis.yml
- test/run-module-bundlers-smoketests.sh
This pull request applies some minor fixes to the module bundlers tests with webpack 4 (which were recently failing on the CI jobs because of the some minor incompatibilities between webpack 3 and webpack 4 cli tool).
> chore(test): Fixed module bundlers tests on webpack 4

- src/browser-polyfill.js
- test/fixtures/runtime-messaging-extension/background.js
- test/fixtures/runtime-messaging-extension/content.js
- test/integration/test-runtime-messaging-on-chrome.js
- test/test-runtime-onMessage.js
This pull requests contains a reworked version of Rob's pull request #22 which aimed to fix #16 by implementing a wrapper for the runtime.onMessage API event which would behave similarly to how it works natively on Firefox (and described in the related API docs on MDN).
Starting from the original #22 pull request, I applied the following changes:
- fixes on the runtime.onMessage listener wrapper to implement the following two scenario as in Firefox:
- when the listener calls the sendResponse but also returns a promise, the sendResponse calls should be ignored (basically the returned promise has an higher precedence and it will override any sendResponse calls, both synchronously called in the listener or asynchronously called after the listener returns)
- the listener return value is used …
> feat: Added support for the sendResponse callback in the runtime.onMessage listeners

- Gruntfile.js
This avoids got inconsistent line breaks and hash for `browser-polyfill.min.js` when build on Windows.
ref: https://github.com/gruntjs/grunt-contrib-concat/issues/20#issuecomment-15540197
> Always use LF for dist files

- api-metadata.json
I looked at the list of namespaces from https://github.com/mozilla/webextension-polyfill/pull/122#issuecomment-394020917 and added those which were missing to the metadata.
See the individual commit messages for more information.
With this PR (and #125), the metadata should be up-to-date, except for the `privacy` namespace.
Fixes #38
> feat: Add missing namespaces to metadata

- api-metadata.json
I have auto-generated the schema signatures for Chrome 54 and Chrome 67, and manually merged the result, as follows:
- Ensure that the keys are alphabetically sorted.
- Remove keys that are not implemented by either browser.
- Add methods that are supported by both Firefox and Chrome.
- Add fallbackToNoCallback where needed.
This PR only modifies existing namespaces. Missing namespaces will be added by other PRs.
Fixes #26 
Fixes #93 
The diff between the output of #122 and the api-metadata after this is as follows (I added comments to explain the discrepancies):
```diff
164,178d163
The tool from #122 does not generate the devtools namespace
<   "devtools": {
<     "inspectedWindow": {
<       "eval": {
<         "minArgs": 1,
<         "maxArgs": 2
<       }
<     },
<     "panels": {
< …
```
> fix: Update existing namespaces in api-metadata.json

- test/setup.js
Now that jsdom/jsdom#1622 has been fixed, and the minimum supported Node version for running the tests is 8 (which has the relevant fix), the relevant follow‑up from #2 can be applied.
> Use `delete window.browser` in `setupTestDOMWindow`

- test/run-browsers-smoketests.sh
- test/run-module-bundlers-smoketests.sh
This fixes the `\n` character sequence preceding all `echo` output in the shell scripts:
eg.: https://travis-ci.org/mozilla/webextension-polyfill/builds/394310210#L2181
> Fix the `\n` character preceding `echo` output in shell scripts

- src/browser-polyfill.js
- test/fixtures/runtime-messaging-extension/background.js
- test/fixtures/runtime-messaging-extension/content.js
- test/test-runtime-onMessage.js
This PR contains the changes from #131 with the addition of some small tweaks (from the last review on #131) and an additional integration test (to check that the behavior of the polyfill in Chrome is the same of the one on Firefox with the native promised APIs).
Fixes #130
> fix: sendMessage promise should resolve to undefined when no listeners reply

- package.json
[`pnpm`](https://pnpm.js.org) is the third largest node package manager, which uses symlinks, hardlinks and isolated trees, which prevents packages from using packages which they haven’t declared in their dependencies.
> Fix tests when installed using pnpm

- src/browser-polyfill.js
- test/fixtures/privacy-setting-extension/background.js
- test/fixtures/privacy-setting-extension/content.js
- test/fixtures/privacy-setting-extension/manifest.json
- test/integration/test-extensions-in-browser.js
This PR adds promise support for the common subset of methods in the `privacy` namespace that are supported by both Chrome and Firefox.
In the future, we can consider extending the promise support to all objects in the `privacy` namespace, even if they are only supported by one browser.
Note that CI will currently fail because of bug #81 (which will be fixed by #132).
Supersedes and closes #44.
> feat: Support promises in privacy namespace

- CONTRIBUTING.md
- README.md
This PR goals is to apply some changes to the README.md file to make it a bit more oriented to the kind of information that may be helpful to an extension developer that just wants to use the library instead of building it from its sources, and move the information about building, testing into a separate CONTRIBUTING.md file.
Here is a link to get a preview of how the README.md is going to look like: https://github.com/rpl/webextension-polyfill/blob/doc/rewrite-readme/README.md 
TODO list:
README.md
CONTRIBUTING.md
> doc: Rewrite README.md and move build and contribution details into a separate doc file

- src/browser-polyfill.js
See @rpl’s comment in https://github.com/mozilla/webextension-polyfill/pull/142#issuecomment-405595998.
> chore: Replace post-processed warning message with single-line string literal

- src/browser-polyfill.js
- test/fixtures/detect-existing-browser-api-object/background.html
- test/fixtures/detect-existing-browser-api-object/background.js
- test/fixtures/detect-existing-browser-api-object/content.js
- test/fixtures/detect-existing-browser-api-object/copy-original-api-objects.js
- test/fixtures/detect-existing-browser-api-object/manifest.json
- test/fixtures/index.html
- test/integration/test-extensions-in-browser.js
- test/setup.js
This PR applies some changes to the webpage used by the integration test suite, to reproduce the same issue that is described in this [comment on issue #68](https://github.com/mozilla/webextension-polyfill/issues/68#issuecomment-406785652) and on https://crbug.com/865881
And the additional check `browser instanceof window.Node` in the polyfill sources, to detect this scenario and prevent the DOM node to be detected as an existing Extension API object (and turn the polyfill into a no-op as when it runs on Firefox where the browser API object is natively available).
> fix: Prevent a webpage document element to be detected as the Extension API object when running in content scripts

- src/browser-polyfill.js
See https://github.com/mozilla/webextension-polyfill/pull/114#pullrequestreview-130858909, https://github.com/mozilla/webextension-polyfill/pull/114#issuecomment-399218317 and https://github.com/mozilla/webextension-polyfill/pull/114#issuecomment-401600755.
This is a breaking change, which will cause #114 and <strike title="merged">#140</strike> to require rebasing.
---
review?(@rpl)
> refactor: Make the `wrapAPIs` function take the `chrome` object as a parameter

- README.md
Chrome 70.0.3538.77 did not find `browser` if the polyfill was loaded last/second (using [the `favorite-color` extension](https://github.com/mdn/webextensions-examples/tree/master/favourite-colour))
> docs(README): Added reminder to include browser-polyfill.js before other bg scripts

- api-metadata.json
- src/browser-polyfill.js
- test/fixtures/devtools-extension/background.js
- test/fixtures/devtools-extension/content.js
- test/fixtures/devtools-extension/devtools_page.html
- test/fixtures/devtools-extension/devtools_page.js
- test/fixtures/devtools-extension/manifest.json
- test/integration/setup.js
- test/integration/test-extensions-in-browser.js
This PR includes the changes needed to ensure that browser.devtools.inspectedWindow.eval returned promise is always resolved to an array (fix #168), and a new integration test to verify it as part of the automated tests.
> fix: browser.devtools.inspectedWindow.eval promise should always resolve to an array

- test/fixtures/devtools-extension/content.js
- test/fixtures/tape-standalone.js
- test/integration/setup.js
This fixes the intermittent timeout issue that caused a #171 test to fail.
- https://travis-ci.org/mozilla/webextension-polyfill/builds/487787360#L950
> test(devtools): Fix intermittent DevTools API test timeout

- src/browser-polyfill.js
- test/setup.js
- test/test-browser-global.js
- test/test-proxied-properties.js
> fix: Throw error when loaded in non-extension contexts

- README.md
Closes #156 as suggested in https://github.com/mozilla/webextension-polyfill/issues/156#issuecomment-464806971 and [as used by Refined GitHub](https://github.com/sindresorhus/refined-github/blob/673b90073e3a030d24f0485c8a457b4452c643c8/webpack.config.js#L37-L50)
> docs(README): Add suggested webpack usage

- api-metadata.json
Fixes #184 
@Rob--W , Let me know if other changes are required. :)
Thanks a lot!
> Removed runtime.getBrowserInfo() 

- .editorconfig
This adds an [EditorConfig] file, so that the project’s indentation style is maintained without needing to reconfigure the editor.
---
[EditorConfig]: https://editorconfig.org
review?(@Rob--W)
> chore: Add `.editorconfig`

- package.json
Fix chromedriver failure triggered by Travis CI. See -> https://travis-ci.org/mozilla/webextension-polyfill/builds/604662201#L568
> chore(deps): Updated chromedriver to version 78.0.1

- src/browser-polyfill.js
- test/test-proxied-properties.js
This PR is for fixing https://github.com/mozilla/webextension-polyfill/issues/204
> fix: Added missing chrome privacy api settings

- package.json
- test/test-async-functions.js
This PR covers the npm dependencies that are outdated and can be updated without any actual change, or with just a very small amount of changes (like the ones applied to update sinon to version 7.5.0).
The following outdated deps are not being updated yet in this PR:
```
Package              Current  Wanted  Latest  Location
babel-preset-babili   0.0.10  0.0.10   0.1.4  webextension-polyfill
grunt-babel            6.0.0   6.0.0   8.0.0  webextension-polyfill
jsdom                 9.12.0  9.12.0  15.2.1  webextension-polyfill
```
jsdom 15.2.1 is not yet updated in this PR because there are backward incompatible changes to the jsdom APIs we use in our test harness, I'm going to take care of that in a separate PR that also port that parts to the new jsdom API.
grunt-babel 8.0.0 isn't yet …
> chore: Update npm dev dependencies (besides jsdom, and the ones related to babel)

- .travis.yml
We moved from IRC to Matrix.
... but the project is stable with little new development so we can as well remove the notifications.
> chore: Remove IRC notification from Travis

- .travis.yml
- package.json
- test/fixtures/tabs-sendmessage-extension/content.js
CI is currently failing because package.json refers chromedriver `^80.0.1`, which also matches 80.0.2.
In 80.0.2, chromedriver updated the `extract-zip` dependency:
https://github.com/giggio/node-chromedriver/commit/16151de4c7bd87ef952665deb95aa56ce3539948
extract-zip 2.0.0 has dropped support for Node <10, e.g. by using APIs that were introduced in Node 10:
https://github.com/maxogden/extract-zip/blob/v2.0.0/index.js#L11
which triggers the following error when run on earlier versions of Node:
```
> chromedriver@80.0.2 install /home/travis/build/mozilla/webextension-polyfill/node_modules/chromedriver
> node install.js
internal/util.js:214
throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
^
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type …
```
> fix(travis): Run tests with Node 10 instead of 8

- README.md
Usage of copy-webpack-plugin has been updated in [v6.0.6](https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v6.0.0).
> docs(README): Updated code in "Usage with webpack without bundling"

- scripts/run-module-bundlers-smoketests.js
Currently the build/test fails with the following output:
```
Test webextension-polyfill bundled with webpack
===============================================
[webpack-cli] Unknown argument: --output
[webpack-cli] Unknown argument: /tmp/webpack-bundle.js
? Which flags do you want to use? …
✔ --entry: The entry point(s) of your application e.g. ./src/main.js
✔ --config: Provide path to a webpack configuration file e.g. ./webpack.config.js
✔ --color: Enable/Disable colors on console
✔ --merge: Merge two or more configurations using webpack-merge e.g. -c ./webpack.config.js -c ./webpack.test.config.js --merge
✔ --progress: Print compilation progress during build
✔ --help: Outputs list of supported flags
✔ --output-path: Output location of the file generated by webpack e.g. ./dist/
``` …
> fix: replace --output option of webpack

- package.json
- test/fixtures/tabs-sendmessage-extension/content.js
CI build is currently broken.
Surprisingly similar to #238: this PR updates the test expectation for a fixed regression in Firefox, and updated chromedriver.
> fix(test): fix expectation of tabs-sendmessage in Firefox + update chromedriver

- src/browser-polyfill.js
- test/test-onRequestFinished.js
Fixes #249.
This updates `browser.devtools.network.onRequestFinished` to emit an
object with a promisified `getContent()` property. This brings the
polyfill implementation in line with Firefox's implementation, although
documentation is still inaccurate at the moment.
Also updates some out of date documentation with `makeCallback()`.
I tested this in my own Chrome extension and it appears to work as expected.
> fix: wrap `onRequestFinished` to use promises

- package.json
Supersedes #277.
Context: looking back to the repo history it looks that the async-wait-until dev dependency was originally used in the integration tests, before we migrated the integration tests to use selenium webdriver to let us run the same set of tests on both Chrome and Firefox. Once we migrated to selenium webdriver async-wait-until did become unused (the integrated tests setup.js module is currently using `driver.wait` for a purpose similar to what async-wait-until was originally used for).
> chore: Removed unused async-wait-until dev dependency

- src/browser-polyfill.js
- test/fixtures/detect-existing-browser-api-object/content.js
- test/fixtures/detect-existing-browser-api-object/manifest.json
- test/test-async-functions.js
Same as #258, re-created to double-check if circle CI would run the CI job as expected. 
Fixes #257
Apart from cross-browser compatibility, this also follows this suggestion https://eslint.org/docs/rules/prefer-promise-reject-errors
> fix: Reject with real Error instances like Firefox does

- README.md
- webextension-polyfill-ts is now [@types/webextension-polyfill](https://www.npmjs.com/package/@types/webextension-polyfill)
- Added a link to [mockzilla-webextension](https://lusito.github.io/mockzilla-webextension/), a unit-testing framework designed for web-extensions.
> Updating readme for typescript definitions and unit-testing

- .circleci/config.yml
- test/setup.js
This PR includes an alternative approach to #344 
The resulting code coverage mapping is not yet right (in both this PR and #344), which is due to the fact that the sourcemap is generated by babel while converting the script into an UMD module, but after grunt-replace is used to interpolated the api-metadata.json data into the script.
I've verified locally that by manually replacing the content of api-metadata.json into the source file, than this PR does generate the expected mapping between the code coverage data collected and the original source file.
This PR is meant to be enough to ensure that codecov will detect and visibly report to us with a failure when a PR is decreasing the code coverage stats.
As a followup we could look into using babel to interpolate the api-metadata.json …
> chore: Fix missing codecov reports

- .eslintrc
- test/fixtures/detect-existing-browser-api-object/content.js
If there's a lint, follow it and enforce it, otherwise it just adds noise.
```
❯ grunt eslint
Running "eslint:src" (eslint) task
Running "eslint:test" (eslint) task
./test/fixtures/detect-existing-browser-api-object/content.js
40:42  warning  Strings must use doublequote  quotes
41:14  warning  Strings must use doublequote  quotes
43:30  warning  Strings must use doublequote  quotes
48:36  warning  Strings must use doublequote  quotes
50:36  warning  Strings must use doublequote  quotes
51:47  warning  Strings must use doublequote  quotes
✖ 6 problems (0 errors, 6 warnings)
0 errors and 6 warnings potentially fixable with the `--fix` option.
Done.
```
```
grunt eslint
Running "eslint:src" (eslint) task
Running "eslint:test" (eslint) task
Done.
```
> Lint: Enforce quotes

- .eslintrc
- src/.eslintrc
- src/browser-polyfill.js
- Actually fixes https://github.com/mozilla/webextension-polyfill/issues/156
Rereading [my last attempt](https://github.com/webpack/webpack/issues/6226#issuecomment-720622514) at dissuading webpack developers to fix ProvidePlugin’s awkward self-providing behavior, I realized that there must be a way to fool webpack into ignoring this replacement.
```js
plugins: [
new ProvidePlugin({
browser: "webextension-polyfill"
})
]
```
ProvidePlugin looks for the raw `browser` variable and replaces it; Turning it into a `window` property access should break it — if not, `typeof window["brow" + "ser"]` certainly will.
This change should be non-breaking, as an alternative solution to https://github.com/mozilla/webextension-polyfill/issues/350 — rather, as a stopgap solution to it.
> Enable usage via `ProvidePlugin`

- .circleci/config.yml
CI job are currently failure the setup part of the integration tests, when we are installing xserver-xephyr from API, e.g.:
- https://app.circleci.com/pipelines/github/mozilla/webextension-polyfill/309/workflows/6e9354f7-00ac-481f-8ee4-775297bc1701/jobs/319/parallel-runs/0/steps/0-115
The error seems to suggest that the apt packages list may be outdated, this PR calls `apt update` right before `apt install` to confirm if that is actually the case.
> chore: Run `apt update` before installing xserver-xephyr in the CI job

- .circleci/config.yml
- package.json
- migrate to the cimg/node docker image
- added (and invoked) the circleci/browser-tools-org (needed to be able to run the integration tests on Firefox and Chrome)
- update chromedriver to v99 and geckodriver to v3 (to make sure they will support also more recent version of Firefox and Chrome)
Filed also a followup for further changes to the circleci config if renovatebot is unable to detect updates needed to the cimg/node docker images with the yaml config as is.
> chore(ci): Updated circleci to use the new cimg/node docker images

- src/browser-polyfill.js
Mini proposal to simplify the detection code. Feel free to reject it if the drawbacks are too great.
- Readable code
- ES2020, yo
- It breaks pre-ES2020 build pipelines unless you add a babel transform for it (but I think `babel/preset-env` should already cover it 🤔) and transpile it down
> Use optional chaining to simplify the detection code

- CONTRIBUTING.md
- package.json
tap-nirvana doesn't seem to be mantained and one of its dependency has a security advisor and it seems to be pinned in tap-nirvana dependency.
It would be nice to replace it with an alternative tap protocol formatter, there is tap-mocha-reporter which looks like a good candidate, but that unfortunately requires some more work to get a nice output and don't lose any of the details that tap-nirvana.
In the meantime tape default output will still provide all details to investigate failures, and it is still readable (just not nicely formatted).
> chore(deps): removed tap-nirvana from the dev dependencies

- src/browser-polyfill.js
> fix: Remove obsolete deprecation warning logged on sendResponse callback calls

- src/browser-polyfill.js
The `browser` object is not a direct descendant of `Object.prototype` in Safari. This check should use `instanceof` for a more compatible check.
> Fix no-op check to work with Safari and support of old browsers

- .circleci/config.yml
- package.json
- test/test-browser-global.js
This PR includes a set of changes needed to fix the CI job failures currently hit due to mismatch between the Chrome version installed in the CI jobs and the Chrome versions supported by the chromedriver dev dependencies (and so it supersedes also PR #573).
Along with that change this PR is also:
- updating the nodejs version used in the CI jobs (from node 14 to node 20)
- fixing a unit test to match the new expected behavior with the changes applied from #582
- updating the inline comment that mention the circleci cli command to use to run the CI job locally on docker (updated to the command line options expected by more recent version of the circleci cli tool)
- updating the geckodriver dependency (from 3.2.0 to 4.3.3, and so this PR also supersedes PR #541)
> chore: chromedriver and geckodriver dependencies along with circleci config

- .circleci/config.yml
- CONTRIBUTING.md
- package.json
Changes made in #597 accidentally resulted in `webpack` and `webpack-cli` being added as dependencies in the manifest of the published package. This problem can be seen in v0.11.0. For more information, see #604.
`webpack` and `webpack-cli` are used for bundler smoke tests that are run in CI. Rather than being installed during CI, these dependencies are now included in `devDependencies`. A new npm script has been added for running this script as well, to ensure that these dependencies are on the PATH when this script is run.
The CircleCI config and the contributor docs have been updated to use the new npm script. You can test it by running
`npm run test-module-bundlers-smoketest`.
Fixes #604
> fix: Remove webpack and webpack-cli dependencies

- .circleci/config.yml
- package.json
This PR updates circleci/browser-tools orb to version 1.5.3, there is an unexpected issue hit by recently created (e.g. like this [one](https://app.circleci.com/pipelines/github/mozilla/webextension-polyfill/1108/workflows/e7e42056-c874-452b-8912-ed8892ea1011/jobs/1128)) that may be due to this.
> chore: update circleci/browser-tools orb to version 1.5.3
